¿Cuál de las siguientes afirmaciones puede ser compatible con el día 6 del ciclo ovárico, en un ciclo de 28 días, en condiciones normales?*a.El ovario presenta folículos primordiales y niveles de FSH en sangre elevados.*b.El ovario presenta folículos con ovocitos en segunda fase de división meiótica.*c.El ovario presenta folículos de De Graaf y niveles de LH en sangre en su pico más alto.*d.Ninguna es correcta.*a*
¿Cuál de las siguientes afirmaciones es correcta?*a.Las células mioepiteliales de la glándula mamaria forman parte del epitelio secretor.*b.El corion liso se localiza en la zona de la decidua capsular.*c. La hoja parietal de la capsula de Bowman tiene epitelio prismático simple.*d. La porción delgada descendente del asa de Henle es impermeable al agua*b*
La observación microscópica de una estructura tubular con vellosidades, tapizadas por un epitelio prismático simple concélulas ciliadas y secretoras, le sugiere que se trata de:*a.Un endometrio en fase secretora.*b.El endocérvix.*c.La trompa de Falopio.*d.El duodeno.*c*
Indique cuál de las siguientes afirmaciones es correcta*a.El lobulillo clásico está delimitado por delgados tabiques conjuntivos.*b.Los conductillos biliares se denominan también conductos de Hering.*c.Los conductos alveolares se localizan entre la 17 y la 19 generación.*d.El epitelio pigmentario está en contacto con la túnica media de la retina.*d*
La observación microscópica del riñón, en la región cortical, pone de relieve la presencia de una estructura tubular con epitelio prismático con células claras y oscuras ¿Cuál de las siguientes afirmaciones es correcta en relación con dicha estructura?*a. La aldosterona aumenta la reabsorción de sodio.*b. Se reabsorbe glucosa.*c. Es impermeable al agua.*d.Corresponde al túbulo contorneado distal*a*
Indique cuál de las siguientes afirmaciones es correcta*a.Los cartílagos laríngeos son fibrosos y elásticos*b.Los cartílagos laríngeos son hialinos y elástico*c.Los cartílagos laríngeos son hialinos y fibrosos*d.Los cartílagos laríngeos no son ni fibrosos ni elásticos*b*
Indique cuál de las siguientes afirmaciones es correcta*a.Las glándulas labiales están en la vertiente externa del labio.*b.La esclerótica es la túnica media del globo ocular.*c.Los hepatocitos son las paredes del canalículo biliar.*d.Los senos paranasales son estructuras vasculares de las fosas nasales*c*
¿Cuál de las siguientes afirmaciones es correcta?*a.El esfínter esofágico inferior (EEI) participa en el inicio de la deglución.*b.La hipoxia puede provocar una activación endotelial.*c.Las glándulas ceruminosas son glándulas sudoríparas ecrinas modificadas que producen el cerumen en el conducto auditivo externo.*d.La presencia de las células de Langerhans que existen en el epitelio pavimentoso estratificado no queratinizado del esófago se detecta porque expresan CD3+ CD8+.*b*
¿Cuál de las siguientes afirmaciones es correcta?*a.La capa muscular interna de los uréteres, tiene disposición longitudinal.*b.La mucosa de la vejiga NO tiene uroplaquinas.*c.Las células productoras de renina se localizan en el mesangio extraglomerular.*d.El corion frondoso se localiza en la zona de la decidua parietal.*a*
¿Cuál de las siguientes afirmaciones es correcta?*a.La célula de Merkel localizada en el estrato espinoso interviene en la percepción sensorial cutánea (mecanorreceptores de adaptación lenta) mediando la sensación táctil.*b.El movimiento hacia afuera de los estereocilios de las células vestibulares deforma la membrana plasmática y abriendo los canales iónicos y permite la entrada de K+ que desencadena la despolarización.*c.Las células musculares lisas de la túnica adventicial de las anastomosis arteriovenosas están muy inervadas y son sustituidas por células epiteliodes.*d.De la capa interna de la muscular de la mucosa surgen unas prolongaciones musculares en forma ascendente hacia el corion (prolongaciones mayores) que circunscriben pequeños territorios, que se les denomina Áreas territoriales o Lobulillo gástrico.*d*
La observación microscópica, en la corteza ovárica, de un ovocito rodeado de una capa de células cúbicas, y todo ello rodeado de estroma, es compatible con:*a.Un folículo primordial.*b.Un folículo cuyo ovocito está detenido en segunda división meiótica.*c.Un folículo secundario.*d.Un folículo primario.*d*
¿Cuál de las siguientes afirmaciones es correcta?*a.La túnica media de las arterias tipificadas como de gran calibre presentan gran cantidad de láminas elásticas fenestradas (70-40), células musculares lisas, fibras de colágena y proteoglucanos y no se observan fibroblastos.*b.La caja del tímpano posee en la pared dos ventanas la redonda ocupada por la platina del estribo y la oval ocupada por una membrana fibrosa.*c.Las glándulas cardiales esofágicas son tubulares serosas algo tortuosa y a veces ramificadas que producen moco neutro (MUC6) y protegen el esófago del reflujo del contenido gástrico que se presenta en la enfermedad por reflujo gastroesofágico (ERGE).*d.Los gránulos de queratohialina que se observan en los queratinocitos granulosos de la epidermis están desprovistos de membrana y estarían constituidos por tonofilamentos CK10 asociados a proteínas (filagrina).*a*
¿Cuál de las siguientes afirmaciones es correcta?*a.La barrera de filtración de la orina retiene partículas de tamaño superior a 10 nm.*b.Ninguna es correcta.*c.Las células del túbulo contorneado distal tienen receptores para parathormona.*d.El ectropión cervical es una alteración patológica.*a*
Indique cuál de las siguientes afirmaciones es correcta*a.El musculo ciliar tiene células musculares estriadas.*b.Las papilas filiformes contienen corpúsculos gustativos.*c.Los conductillos biliares vierten la bilis a los colangiolos.*d.Los bronquiolos respiratorios se localizan entre la 17 y la 19 generación*d*
¿Cuál de las siguientes afirmaciones es correcta?*a.Las nefronas yuxtamedulares contiene asas de Henle, cortas.*b.Ninguna es correcta*c.La barrera de filtración de la orina está constituida por en endotelio fenestrado, membrana basal gruesa y una especialización de la capa visceral de la cápsula de Bowman*d.La barrera de filtración de la orina está constituida por un mesotelio fenestrado, membrana basal gruesa y una especialización del capa visceral de la cápsula de Bowman*c*
La observación microscópica de un endometrio cuyas células epiteliales presentan glucógeno en el polo apical, puede corresponder temporalmente con:*a.Un ovario cuyos folículos están elaborando fundamentalmente estrógenos.*b.Un ovario donde se podría observar claramente, un folículo atrésico.*c.Un endometrio en fase proliferativa.*d.Un ovario cuyos folículos están elaborando fundamentalmente progesterona.*b*
Indique cuál de las siguientes afirmaciones es correcta*a.La colágena es la materia orgánica principal de la dentina y el cemento.*b.La colágena es la materia orgánica principal del esmalte y la pulpa*c.La colágena es la materia orgánica principal del esmalte y el cemento.*d.La colágena es la materia orgánica principal de la dentina y el esmalte*a*
